// <auto-generated />
using AKHILAPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AKHILAPP.Migrations
{
    [DbContext(typeof(AkhilAppDbcontext))]
    partial class AkhilAppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AKHILAPP.Models.Category_Master", b =>
                {
                    b.Property<int>("CatMaster_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatMaster_Id"));

                    b.Property<string>("Cat_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatMaster_Id");

                    b.ToTable("Category_Masters");
                });

            modelBuilder.Entity("AKHILAPP.Models.Product_Master", b =>
                {
                    b.Property<int>("ProdMaster_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdMaster_Id"));

                    b.Property<int>("Catmaster_Id")
                        .HasColumnType("int");

                    b.Property<string>("Prod_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdMaster_Id");

                    b.HasIndex("Catmaster_Id");

                    b.ToTable("Product_Masters");
                });

            modelBuilder.Entity("AKHILAPP.Models.Product_Master", b =>
                {
                    b.HasOne("AKHILAPP.Models.Category_Master", "Category_Master")
                        .WithMany("Product_Masters")
                        .HasForeignKey("Catmaster_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_Master");
                });

            modelBuilder.Entity("AKHILAPP.Models.Category_Master", b =>
                {
                    b.Navigation("Product_Masters");
                });
#pragma warning restore 612, 618
        }
    }
}
